import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client"; // Import UserProvider

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-y-scroll" lang="en">
      <body className={poppins.className}>
        <UserProvider>
          {" "}
          {/* Wrap the entire app with UserProvider */}
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
